import type { Copy } from './copy.en';

export const copyZh: Copy = {
  nav: {
    home: '首页',
    services: '服务',
    portfolio: '作品集',
    classes: '课程',
    book: '立即预订',
  },
  landing: {
    heroEyebrow: 'KIKI · 吉隆坡甲洞',
    heroHeadline: '韩式新娘与活动彩妆',
    heroSub: '柔和自然、上镜的妆容。工作室位于吉隆坡甲洞。',
    heroCta: '预订您的档期',
    heroCtaSecondary: '查看作品',
  },
  booking: {
    title: '预订档期',
    stepService: '选择服务',
    stepSlot: '选择时间',
    stepDetails: '您的资料',
    stepReview: '确认详情',
    nameLabel: '姓名',
    phoneLabel: 'WhatsApp 号码',
    emailLabel: '电子邮件(选填)',
    notesLabel: '备注',
    submit: '提交预订',
    submittingFallback: '提交中…',
    successTitle: '已收到您的预订',
    successBody: 'Kiki 很快会通过 WhatsApp 确认,请留意您的手机。',
    errorTitle: '出现问题',
    errorSlotTaken: '该时段刚被预订,请选择其他时间。',
  },
  services: {
    eyebrow: '服务项目',
    title: '每一款妆,都有它的价。',
    bookThisLabel: '预约此项 →',
    footnote:
      '所有价钱含护肤、假睫毛、造型、配饰。RM100 订金确认档期。外出服务另加交通费（RM30–80，视地区而定）。',
  },
  location: {
    eyebrow: '地点 · 联络',
    title: '来找我或发 WhatsApp。',
    address: 'Sri Delima MRT 站附近，甲洞，吉隆坡（详细地址 WhatsApp 发送）',
    whatsappCta: '发 WhatsApp',
    whatsappDisplay: '+60 17-920 2880',
  },
  faq: {
    eyebrow: '常见问题',
    title: '先来解答。',
    items: [
      {
        id: 'book',
        question: '要怎么预约?',
        answer:
          '在上方填写预约表单，我会通过 WhatsApp 确认，交付 RM100 订金锁定档期。',
      },
      {
        id: 'included',
        question: '价钱包括什么?',
        answer:
          '全包：妆前护肤、修眉、假睫毛、造型、身体提亮、演出水钻、头饰配件。无隐藏收费。',
      },
      {
        id: 'travel',
        question: '外出服务有交通费吗?',
        answer: '是的，视地区 RM30–80。工作室服务无需交通费。',
      },
      {
        id: 'beauty-filter',
        question: '拍妆会修图美颜吗?',
        answer:
          '所有照片皆原相，只微调亮度。无重度滤镜，所见即所得。',
      },
      {
        id: 'cancel',
        question: '可以取消吗?',
        answer: '订金不退，但可提前合理通知改期。',
      },
    ],
  },
  footer: {
    rights: '© Kiki Studio',
    instagramCtaLabel: '关注我们的 Instagram',
  },
  pages: {
    servicesTitle: '服务',
    servicesSubtitle: '完整价目,清楚明白。',
    servicesBookLabel: '预约',
    portfolioTitle: '作品集',
    portfolioSubtitle: '最近的一些妆容作品。',
    classesTitle: '课程',
    classesBody:
      'Kiki 的韩式彩妆课程即将推出。请过几周再回来看看,或关注 Instagram 留意最新公告。',
    durationUnitShort: '分钟',
  },
  admin: {
    signIn: {
      title: '管理员登录',
      emailLabel: '邮箱',
      submit: '发送登录链接',
      submitting: '发送中…',
      checkEmailTitle: '请查收邮件',
      checkEmailBody: '如该邮箱在授权列表中,我们已发送登录链接,15 分钟内有效。',
      errors: {
        generic: '出错了,请重试。',
        expired: '链接已过期,请重新发送。',
      },
    },
    header: {
      brand: 'Kiki Studio 后台',
      signedInAs: '已登录为',
      signOut: '退出',
    },
    revenue: {
      thisMonth: '本月',
      confirmed: '已确认',
      pending: '待处理',
      upcoming: '即将到来',
    },
    tabs: {
      pending: '待处理',
      upcoming: '即将到来',
      past: '历史',
    },
    search: {
      placeholder: '按姓名、电话或服务搜索…',
      submit: '搜索',
      noResults: '没有匹配的预约。',
    },
    pagination: {
      previous: '上一页',
      next: '下一页',
      pageOf: '第 {current} 页,共 {total} 页',
    },
    booking: {
      durationUnit: '分钟',
      statusLabels: {
        pending: '待处理',
        confirmed: '已确认',
        rejected: '已拒绝',
        completed: '已完成',
        cancelled: '已取消',
        no_show: '未出席',
      },
      locationLabels: {
        studio: '工作室',
        home: '上门',
        venue: '场地',
      },
      customerNoteHeader: '客户备注',
      adminNoteHeader: '管理员备注',
      auditTrailHeader: '操作记录',
      confirmAction: '确认',
      rejectAction: '拒绝',
      confirming: '确认中…',
      rejecting: '拒绝中…',
      rejectReasonLabel: '原因(可选,将分享给客户)',
      rejectReasonPlaceholder: '那个周末已约满…',
      rejectSubmit: '确认拒绝',
      rejectCancel: '取消',
      notifyFailedBanner: '{name} 的客户通知未能发送。',
      resendAction: '重新发送',
      alreadyHandled: '此预约已处理。',
    },
    actions: {
      confirmHeading: '确认此预约?',
      confirmBody: '点击下方按钮后,预约将被标记为已确认,并向客户发送通知邮件。',
      confirmButton: '确认预约',
      confirmedHeading: '预约已确认',
      confirmedBodyWithNotifyOk: '客户已收到通知。',
      confirmedBodyWithNotifyFail: '已确认,但未能发送客户通知邮件。请登录后台重试。',
      rejectHeading: '拒绝此预约?',
      rejectBody: '可选填写简短原因分享给客户,然后点击下方按钮。',
      rejectButton: '确认拒绝',
      rejectedHeading: '预约已拒绝',
      invalidLink: '此链接无效或已被篡改。',
      expiredLink: '链接已过期,请登录后台处理此预约。',
      notFound: '未找到该预约。',
    },
    audit: {
      events: {
        booking_created: '预约已创建',
        booking_confirmed: '已确认',
        booking_rejected: '已拒绝',
        notify_sent: '客户已通知',
        notify_failed: '客户通知失败',
      },
    },
  },
};
